### ISSUE TITLE
Problem:  Pricing page is brittle and hard to maintain.

### ISSUE THREAD

**Issue by sliptonic** [Ondsel-Development/website#20]
As we seek product-market-fit,  we are iterating on the pricing page routinely.  The current page is hard to maintain.  If labels are too long, the layout breaks or appears asymmetric.  

This is low priority but a more flexible pricing page / component would be useful.

**Comment by patdavid** [comment]
This has been addressed in [pat/price-matrix](https://github.com/Ondsel-Development/website/tree/pat/price-matrix) branch.

This is in active development now.
